#!/bin/bash
# install pi-top-battery-widget

if [ `whoami` = root ]; then
  echo "Please run as the user who has started the desktop, not as root"
  exit 1
fi


# kill any running pi-top-battery-widget command so that it can be overwritten
pkill pi-top-battery- 2>/dev/null

# create bin directory in ~, if it does not exist
[ ! -d ~/bin  ] && mkdir ~/bin

#make sure that files are executable
chmod +x pi-top-battery-widget

#copy necessary files to ~/bin
cp battery_icon.png ~/bin
cp pi-top-battery-widget ~/bin

# add line to lxsession autostart, if it does not already exist
if ! grep -q "pi-top-battery-widget" ~/.config/lxsession/LXDE-pi/autostart
then
    cp ~/.config/lxsession/LXDE-pi/autostart ./lxsession_autostart_backup
    echo "@pi-top-battery-widget > /dev/null &" >> ~/.config/lxsession/LXDE-pi/autostart
fi

#restart gtk_battery in background making sure that it lives on if calling console is closed
nohup ~/bin/pi-top-battery-widget > /dev/null 2>/dev/null &
