#!/bin/bash
# Uninstall pi-battery-widget

# kill running pi-battery-widget command
pkill pi-battery-

#remove files from ~/bin
rm ~/bin/battery_icon.png
rm ~/bin/pi-battery-widget
rm ~/bin/pi-battery-reader.py
rm ~/.config/lxpanel/LXDE-pi/panels/redreactor.conf

# remove line from lxsession autostart
cd ~/.config/lxpanel/LXDE-pi/panels
grep -v "pi-battery-widget" ./autostart > temp
mv temp autostart
